name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/topa1212/data/releases/download/daata/datang.zip -OutFile data.zip 

    - name: Extract
      run: Expand-Archive data.zip -DestinationPath "C:\Users\Public\Desktop"
   
    - name: ZIP UNLOCK
      run: | 
        Expand-Archive -Path "C:\Users\Public\Desktop\datang\RTX.zip" -DestinationPath "C:\Users"  
            
    - name: Auth
      run: cmd /c C:\Users\Public\Desktop\datang\ngrok.exe authtoken 22E3jyrO0gYE4w2YZ9jyhkijRvF_6r4bMdXDkZ519JoKAcudb
    
    - name: SET PRO
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Bhupi@1997" -Force)
      
    - name: IP SETUP
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "C:\Users\Public\Desktop\datang\ngrok.exe tcp 3389"'
    
    - name: SET USER
      run: cmd /c del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > out.txt 2>&1
    - run: net config server /srvcomment:"Windows Server 2022 By SMARTPATEL" > out.txt 2>&1
    - run: REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
    - run: net user SMARTPATEL Bhupi@2000 /add >nul
    - run: net localgroup administrators SMARTPATEL /add >nul
    - run: net user SMARTPATEL /active:yes >nul
    - run: diskperf -Y >nul
    - run: sc config Audiosrv start= auto >nul
    - run: sc start audiosrv >nul
    - run: ICACLS C:\Windows\Temp /grant SMARTPATEL:F >nul
    - run: ICACLS C:\Windows\installer /grant SMARTPATEL:F >nul  
   
    - name: IP
      run: C:\Users\Public\Desktop\datang\ip.bat
         
    - name: RUN
      run: C:\Users\RTX\source\repos\rtx\bin\Debug\rtx.exe


      
      
      
