name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/topa1212/data/releases/download/daata/datang.zip -OutFile data.zip 

    - name: Extract
      run: Expand-Archive data.zip -DestinationPath "C:\Users\Public\Desktop"

    - name: Auth
      run: cmd /c C:\Users\Public\Desktop\datang\ngrok.exe authtoken 2drVOznyn53USZzI0vxVYFc0bZp_8arMsfoMVkREwEQ9JTQG
    
    - name: SET BAT
      run: cmd /c C:\Users\Public\Desktop\datang\runonrdp.bat
      
    - name: Enable
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Authh
      run: C:\Users\Public\Desktop\data\ngrok.exe tcp 3389


      
      
      
